<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UA1CCT0" failures="4" tests="17" name="Specific Test" time="0.438" errors="0" timestamp="2022-04-15T13:08:03 IST">
  <testcase classname="TestCases.HardAssertionTest" name="method1" time="0.029"/>
  <testcase classname="TestCases.HardAssertionTest" name="method11" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.HardAssertionTest.method11(HardAssertionTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- method11 -->
  <testcase classname="TestCases.HardAssertionTest" name="method2" time="0.013">
    <failure type="java.lang.AssertionError" message="Failed method2 printing expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: Failed method2 printing expected [200] but found [400]
at TestCases.HardAssertionTest.method2(HardAssertionTest.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- method2 -->
  <testcase classname="TestCases.HardAssertionTest" name="method3" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestCases.HardAssertionTest.method3(HardAssertionTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- method3 -->
  <testcase classname="TestCases.HardAssertionTest" name="method44" time="0.004"/>
  <testcase classname="TestCases.HardAssertionTest" name="method5" time="0.005"/>
  <testcase classname="TestCases.GroupTest" name="method1" time="0.007"/>
  <testcase classname="TestCases.GroupTest" name="method2" time="0.006"/>
  <testcase classname="TestCases.GroupTest" name="method3" time="0.004"/>
  <testcase classname="TestCases.GroupTest" name="method4" time="0.006"/>
  <testcase classname="TestCases.GroupTest" name="method5" time="0.003"/>
  <testcase classname="TestCases.GroupTest" name="method6" time="0.004"/>
  <testcase classname="TestCases.SoftAssertionTest" name="test1" time="0.017"/>
  <testcase classname="TestCases.SoftAssertionTest" name="test2" time="0.006">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	it is failing expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
it is failing expected [true] but found [false]
at TestCases.SoftAssertionTest.test2(SoftAssertionTest.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="TestCases.PriorityTest1" name="method2" time="0.002"/>
  <testcase classname="TestCases.PriorityTest1" name="method5" time="0.002"/>
  <testcase classname="TestCases.PriorityTest1" name="method4" time="0.002"/>
</testsuite> <!-- Specific Test -->
